"use client";

import { useEffect, useState } from "react";

import { PageHeader } from "../components/PageHeader";
import { AuditFilters } from "../components/AuditFilters";
import { useAuth } from "../lib/auth-context";
import { api, ApiError, type ApiAudit } from "../lib/api";

export default function AuditsPage() {
  const { token } = useAuth();
  const [audits, setAudits] = useState<ApiAudit[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!token) return;
    const controller = new AbortController();
    api
      .listAudits(token, controller.signal)
      .then((rows) => {
        if (controller.signal.aborted) return;
        setAudits(rows);
      })
      .catch((err) => {
        if (controller.signal.aborted) return;
        setError(err instanceof ApiError ? err.message : "Failed to load audits");
      })
      .finally(() => {
        if (!controller.signal.aborted) setLoading(false);
      });
    return () => controller.abort();
  }, [token]);

  const total = audits.length;
  const totalFindings = audits.reduce((acc, a) => acc + a.findings.length, 0);
  const critical = audits.reduce(
    (acc, a) => acc + a.findings.filter((f) => f.severity === "CRITICAL").length,
    0,
  );
  const highOrCritical = audits.reduce(
    (acc, a) =>
      acc +
      a.findings.filter(
        (f) => f.severity === "HIGH" || f.severity === "CRITICAL",
      ).length,
    0,
  );

  return (
    <div>
      <PageHeader
        title="Compliance Audits"
        description="Automated regulatory analyses generated by the LLM auditor. Each audit maps document clauses against framework requirements and produces prioritized findings."
      />

      <div className="px-4 sm:px-6 lg:px-8 py-6 space-y-6">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="rounded-xl border border-border bg-surface p-4">
            <div className="text-xs text-muted">Total audits</div>
            <div className="mt-1 text-2xl font-semibold tabular-nums">
              {loading ? "—" : total}
            </div>
          </div>
          <div className="rounded-xl border border-border bg-surface p-4">
            <div className="text-xs text-muted">Total findings</div>
            <div className="mt-1 text-2xl font-semibold tabular-nums">
              {loading ? "—" : totalFindings}
            </div>
          </div>
          <div className="rounded-xl border border-border bg-surface p-4">
            <div className="text-xs text-muted">High or critical</div>
            <div className="mt-1 text-2xl font-semibold tabular-nums text-warning">
              {loading ? "—" : highOrCritical}
            </div>
          </div>
          <div className="rounded-xl border border-border bg-surface p-4">
            <div className="text-xs text-muted">Critical findings</div>
            <div className="mt-1 text-2xl font-semibold tabular-nums text-danger">
              {loading ? "—" : critical}
            </div>
          </div>
        </div>

        {error && (
          <div className="rounded-lg border border-danger/30 bg-danger-soft px-3 py-2 text-xs text-danger">
            {error}
          </div>
        )}

        {loading ? (
          <div className="rounded-xl border border-border bg-surface px-6 py-12 text-center text-sm text-muted">
            Loading audits…
          </div>
        ) : (
          <AuditFilters audits={audits} />
        )}
      </div>
    </div>
  );
}
